name: Auto Assign Issue

on:
  issues:
    types: [opened, edited]

jobs:
  assign:
    # if: ${{ github.event.label.name == '調査・対応依頼' }}
    runs-on: self-hosted
    steps:
      - uses: bubkoo/auto-assign@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: .github/config-auto-assign.yml
